# @format

# Site Info
title: "wndtlr1024's Blog"
tagline: "wndtlr1024"
description: "Commit to myself"
baseurl: ""
url: https://jungsikjeong.github.io/
logo: "/public/logo.png"

# Site configurations
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: "/blog/page:num"
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: JEONG JUNGSIK
  description: 정중식(JEONG JUNGSIK)
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github: https://github.com/jungsikjeong
    #facebook:  https://www.facebook.com/wayhome25
    # twitter:   https://twitter.com/Li_Zhihao
    # facebook: https://velog.io/@wndtlr1024
    email: mailto:wndtlr1024@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - "/blog/"
  Categories:
    - "/"
    # - { Categories All: "/blog/categories/" }
    - { debug: "/blog/categories/#debug" }
    - { memo: "/blog/categories/#memo" }
    - { typescript: "/blog/categories/#typescript" }
    - { wil: "/blog/categories/#wil" }
    - { nestjs: "/blog/categories/#nestjs" }
    # - { git: "/blog/categories/#git" }
    # - { memo: "/blog/categories/#memo" }
    # - { nodejs: "/blog/categories/#nodejs" }
    # - { typeScript: "/blog/categories/#typeScript" }
    # - { nextjs: "/blog/categories/#nextjs" }
    # - { firebase: "/blog/categories/#firebase" }
    # - { Tags: '/blog/tags/' }
  About:
    - "/about/"
  Search:
    - "/search/"

# Where are tags and categories displayed
tag_page: "/blog/tags/"
category_page: "/blog/categories/"

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: "G-50Q171KMMK"
disqus_short_name: "jungsikjeong-github-io" # leave blank if you don't want disqus
codepen_username: "정중식"

# Use the following plug-ins
plugins:
  - jekyll-paginate
timezone: Asia/Seoul
